---
title: "Gov 50 Final Project"
author: "Hana O'Looney"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts - Milestone 1

I am interested in somehow exploring the idea of political polarization in the United States and its connections to the news media, especially broadcast journalism. I think it could be possible to study what people self-report as their main media sources are and see if there is a correlation to their party affiliation or even self-reported candidate preferences or opinions on current events (the existence of climate change, the degree to which polarization or elitist are prevalent issues, etc.). Aside from the more obvious question of what news networks promote certain ideologies, it would also be interesting to study how differences in the medium of news consumption --print versus broadcast versus social media, for example-- impacts peoples' perspectives, if at all. 

## Project Proposal - Milestone 2

I will be using the Fox News rollout data set for my project in order to investigate the question: How does one's broadcast news source impact their political opinions? In order to do so, I am interested in investigating the correlation between the subrf2000 variable, which indicates the share of a certain city that was subscribed to Fox News in 2000, with the gopvoteshare2000 variable, which indicates the share of votes won by Republicans in the 2000 presidential election. I think it would also be interesting to find the correlation between different demographic data and whether or not people are subscribed to Fox News or tend to vote Republican. This can be done with the provided data set by finding the correlation between subrf2000 or gopvoteshare2000 with black1990, indicating the percentage of black people in a certain city, hisp2000, indicating the percentage of hispanic people in a certain city, or even income1990, indicating the median income in a certain city. That way, we can determine if the share of Fox News subscribers has a higher correlation with Republican voting outcomes compared to other possible explanations of race and income, although this analysis will not prove causality as it will simply demonstrate a correlation and the effect could be due to other confounding factors not studied. 

My hypothesis is that one's broadcast news source is highly influential on their political opinions. This hypothesis comes from my personal experiences interning on Capitol Hill, where constituents who would call into our office would often cite commentators on partisan broadcast news networks such as FOX or MSNBC as the evidence and fuel for their opinions on different legislative matters and political candidates. Especially in the United States' current extremely partisan broadcast media landscape, I think that Americans' views on political issues are highly dependent on their news sources. This hypothesis would be proven through this analysis by a high correlation between cities' proportion of Fox News subscribers and GOP vote share, and strengthened if that correlation is even higher than the correlation between GOP vote share and other demographic variables such as the share of Black/Hispanic population or the median income. If the correlation between the proportion of Fox News subscribers and the share of GOP votes is extremely low, or if racial demographics and/or income levels of various communities have a higher correlation with GOP votes compared to Fox News subscribers, this would disprove my hypothesis. 

